#ifndef QTPHYSICSUNOFFICIAL_GLOBAL
#define QTPHYSICSUNOFFICIAL_GLOBAL

#if defined(QTPHYSICSUNOFFICIAL_LIBRARY)
#  define QTPHYSICSUNOFFICIAL_EXPORT Q_DECL_EXPORT
#else
#  define QTPHYSICSUNOFFICIAL_EXPORT Q_DECL_IMPORT
#endif

#include <Qt3DCore>
#if (QT_VERSION > QT_VERSION_CHECK(5, 5, 0))
#include <Qt3DRender>
#else
#include <Qt3DRenderer>
#endif

#endif // QTPHYSICSUNOFFICIAL_GLOBAL
